services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: enterprise-rag-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: enterprise-rag-backend
    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/ragdb
      JWT_SECRET_KEY: development-secret
      APP_ENV: development
      DEBUG: "true"

    ports:
      - "8000:8000"

    depends_on:
      - postgres


volumes:
  postgres_data: