"""enhance document ingestion metadata

Revision ID: ec782d14acc3
Revises: 721ca45b076c
Create Date: 2026-09-17 20:06:36.823801

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec782d14acc3"
down_revision: str | Sequence[str] | None = "721ca45b076c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks", sa.Column("section_title", sa.String(length=500), nullable=True)
    )
    op.add_column("document_chunks", sa.Column("token_count", sa.Integer(), nullable=True))
    op.add_column("documents", sa.Column("stored_filename", sa.String(length=255), nullable=False))
    op.add_column("documents", sa.Column("file_size", sa.Integer(), nullable=False))
    op.add_column("documents", sa.Column("checksum", sa.String(length=64), nullable=False))
    op.add_column("documents", sa.Column("page_count", sa.Integer(), nullable=True))
    op.add_column("documents", sa.Column("error_message", sa.Text(), nullable=True))
    op.add_column("documents", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.create_index(op.f("ix_documents_checksum"), "documents", ["checksum"], unique=False)
    op.create_unique_constraint(None, "documents", ["stored_filename"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "documents", type_="unique")
    op.drop_index(op.f("ix_documents_checksum"), table_name="documents")
    op.drop_column("documents", "updated_at")
    op.drop_column("documents", "error_message")
    op.drop_column("documents", "page_count")
    op.drop_column("documents", "checksum")
    op.drop_column("documents", "file_size")
    op.drop_column("documents", "stored_filename")
    op.drop_column("document_chunks", "token_count")
    op.drop_column("document_chunks", "section_title")
    # ### end Alembic commands ###
